// =============================================================================
// codegen.rs — Code Generator for the Pico compiler
// =============================================================================
//
// The CODE GENERATOR is the final phase of the Pico compiler.
//
// Input:  a fully-checked AST (Abstract Syntax Tree) produced by the parser
//         and validated by the semantic checker.
// Output: a String containing valid TypeScript source code.
//
// ── How it works ─────────────────────────────────────────────────────────────
//   We WALK the AST recursively, visiting every node and converting it to the
//   equivalent TypeScript text.  This is often called "tree-walking" code gen.
//
//   Two main functions:
//     gen_stmt(stmt)  → generates a TypeScript STATEMENT
//     gen_expr(expr)  → generates a TypeScript EXPRESSION and returns a String
//
//   These call each other recursively, mirroring the recursive structure of
//   the AST itself.
//
// ── Pico → TypeScript translation table ──────────────────────────────────────
//
//   Pico                            TypeScript
//   ─────────────────────────────── ────────────────────────────────────────
//   let x = 5;                      const x = 5;
//   let s = "hi";                   const s = "hi";
//   print(x);                       console.log(x);
//   if x > 0 { … }                  if (x > 0) { … }
//   fn add(a, b) { return a+b; }    function add(a: any, b: any): any { … }
//   add(1, 2)                       add(1, 2)
//   x == y                          x === y   ← strict equality in TypeScript
//   x != y                          x !== y   ← strict not-equal
//
// ── Indentation ──────────────────────────────────────────────────────────────
//   We track an `indent_level` counter.
//     level 0 → top-level code  (no indent)
//     level 1 → inside a function or if-block  (4 spaces)
//     level 2 → nested block  (8 spaces)
//   Before emitting each line we prepend `"    ".repeat(indent_level)`.
// =============================================================================

use crate::ast::{BinOp, Expr, Program, Stmt};

// =============================================================================
// CodeGen struct
// =============================================================================
pub struct CodeGen {
    /// Accumulates the final TypeScript output.
    /// We append to this string as we walk the AST.
    output: String,

    /// Current indentation level.
    ///   0 → no indent (top-level)
    ///   1 → 4 spaces  (one block deep)
    ///   2 → 8 spaces  (two blocks deep)
    ///   …
    indent_level: usize,
}

impl CodeGen {
    // -------------------------------------------------------------------------
    // Construction
    // -------------------------------------------------------------------------

    /// Create a new, empty `CodeGen`.
    pub fn new() -> Self {
        CodeGen {
            output: String::new(),
            indent_level: 0,
        }
    }

    // -------------------------------------------------------------------------
    // Low-level output helpers
    // -------------------------------------------------------------------------

    /// Return the correct indentation string for the current `indent_level`.
    ///
    /// Uses 4 spaces per level — a widely-accepted TypeScript convention.
    ///
    /// Examples:
    ///   level 0 → ""
    ///   level 1 → "    "
    ///   level 2 → "        "
    fn indent(&self) -> String {
        "    ".repeat(self.indent_level)
    }

    /// Append one line to the output with the current indentation, followed
    /// by a newline character.
    ///
    /// This is the only method that directly writes to `self.output`,
    /// keeping all output logic in one place.
    fn emit(&mut self, line: &str) {
        self.output.push_str(&self.indent());
        self.output.push_str(line);
        self.output.push('\n');
    }

    /// Append a blank line (just a newline, no indentation).
    /// Used after function definitions to improve readability.
    fn emit_blank(&mut self) {
        self.output.push('\n');
    }

    // -------------------------------------------------------------------------
    // Program-level entry point
    // -------------------------------------------------------------------------

    /// Generate TypeScript for the entire program.
    ///
    /// Prepends a small header comment, then walks every top-level statement.
    /// Returns the complete TypeScript source as a `String`.
    ///
    /// This is the public entry point called from `main.rs`.
    pub fn gen_program(&mut self, program: &Program) -> String {
        // File header — makes the output file clearly identifiable
        self.emit("// Generated by Pico Compiler");
        self.emit("// Do not edit this file by hand — re-run the compiler instead.");
        self.emit_blank();

        for stmt in program {
            self.gen_stmt(stmt);
        }

        self.output.clone()
    }

    // -------------------------------------------------------------------------
    // Statement code generation
    // -------------------------------------------------------------------------

    /// Generate TypeScript for a single statement.
    ///
    /// Each variant of `Stmt` maps to a specific TypeScript construct.
    fn gen_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            // -----------------------------------------------------------------
            // `let name = value;`  →  `const name = <value_ts>;`
            //
            // Pico's `let` maps to TypeScript's `const` because, in Pico,
            // re-assignment is not supported — the value is fixed once bound.
            // TypeScript's `const` communicates that intent to the reader.
            // -----------------------------------------------------------------
            Stmt::Let { name, value } => {
                let value_ts = self.gen_expr(value);
                self.emit(&format!("const {} = {};", name, value_ts));
            }

            // -----------------------------------------------------------------
            // `return expr;`  →  `return <expr_ts>;`
            // -----------------------------------------------------------------
            Stmt::Return(expr) => {
                let expr_ts = self.gen_expr(expr);
                self.emit(&format!("return {};", expr_ts));
            }

            // -----------------------------------------------------------------
            // `if condition { then } else { else }`
            //
            // The condition expression is wrapped in parentheses as required
            // by TypeScript syntax.
            // The body is indented by increasing `indent_level` by 1 while
            // generating the block, then restoring it afterward.
            // -----------------------------------------------------------------
            Stmt::If {
                condition,
                then_block,
                else_block,
            } => {
                let cond_ts = self.gen_expr(condition);

                // Opening line:  `if (<condition>) {`
                self.emit(&format!("if ({}) {{", cond_ts));

                // 'then' block — indented one level deeper
                self.indent_level += 1;
                for s in then_block {
                    self.gen_stmt(s);
                }
                self.indent_level -= 1;

                if let Some(else_stmts) = else_block {
                    // `} else {`
                    self.emit("} else {");
                    self.indent_level += 1;
                    for s in else_stmts {
                        self.gen_stmt(s);
                    }
                    self.indent_level -= 1;
                    self.emit("}");
                } else {
                    // No else branch — just close the `if`
                    self.emit("}");
                }
            }

            // -----------------------------------------------------------------
            // `fn name(a, b) { body }`
            //  →  `function name(a: any, b: any): any { … }`
            //
            // Pico's untyped parameters become `any` in TypeScript because
            // the base version of Pico has no type system.  Adding real types
            // is a great extension exercise for the reader!
            // -----------------------------------------------------------------
            Stmt::Function { name, params, body } => {
                // Build parameter string:  `a: any, b: any`
                let params_ts: Vec<String> = params
                    .iter()
                    .map(|p| format!("{}: any", p))
                    .collect();
                let params_str = params_ts.join(", ");

                // Function signature + opening brace
                self.emit(&format!("function {}({}): any {{", name, params_str));

                // Body — indented
                self.indent_level += 1;
                for s in body {
                    self.gen_stmt(s);
                }
                self.indent_level -= 1;

                self.emit("}");
                self.emit_blank(); // blank line after a function for readability
            }

            // -----------------------------------------------------------------
            // `print(expr);`  →  `console.log(<expr_ts>);`
            //
            // TypeScript's built-in printing function is `console.log`.
            // -----------------------------------------------------------------
            Stmt::Print(expr) => {
                let expr_ts = self.gen_expr(expr);
                self.emit(&format!("console.log({});", expr_ts));
            }

            // -----------------------------------------------------------------
            // Expression statement  (e.g. standalone function call)
            //   `greet("Alice");`  →  `greet("Alice");`
            // -----------------------------------------------------------------
            Stmt::ExprStmt(expr) => {
                let expr_ts = self.gen_expr(expr);
                self.emit(&format!("{};", expr_ts));
            }
        }
    }

    // -------------------------------------------------------------------------
    // Expression code generation
    // -------------------------------------------------------------------------

    /// Generate TypeScript for a single expression.
    ///
    /// Returns the expression as a `String` (not appended to `output`
    /// directly).  This is because expressions are always embedded inside
    /// larger constructs, e.g.:
    ///   `const x = <expression>;`
    ///   `if (<expression>) {`
    fn gen_expr(&mut self, expr: &Expr) -> String {
        match expr {
            // -----------------------------------------------------------------
            // Number literal
            //
            // We strip the trailing ".0" for whole numbers so that:
            //   Pico:  `let x = 42;`
            //   TypeScript:  `const x = 42;`  (not `const x = 42.0;`)
            //
            // But decimal numbers are kept as-is:
            //   Pico:  `let pi = 3.14;`
            //   TypeScript:  `const pi = 3.14;`
            //
            // `fract()` returns the fractional part of an f64.  If it is 0.0,
            // the number has no decimal component.
            // -----------------------------------------------------------------
            Expr::Number(n) => {
                if n.fract() == 0.0 {
                    format!("{}", *n as i64) // e.g. 42
                } else {
                    format!("{}", n) // e.g. 3.14
                }
            }

            // -----------------------------------------------------------------
            // String literal
            //
            // Re-add the double-quotes and escape any literal `"` characters
            // that might be inside the string.
            // -----------------------------------------------------------------
            Expr::Str(s) => {
                // Escape double-quotes inside the string so the output is valid
                let escaped = s.replace('"', "\\\"");
                format!("\"{}\"", escaped)
            }

            // -----------------------------------------------------------------
            // Boolean literal
            //
            // `true` → `"true"`,  `false` → `"false"`
            // Rust's `bool::to_string()` already gives the right text.
            // -----------------------------------------------------------------
            Expr::Bool(b) => b.to_string(),

            // -----------------------------------------------------------------
            // Identifier (variable reference)
            //
            // Variable names map 1:1; no transformation needed.
            // -----------------------------------------------------------------
            Expr::Ident(name) => name.clone(),

            // -----------------------------------------------------------------
            // Binary expression
            //
            // We wrap the whole expression in parentheses:
            //   `(left op right)`
            // This is slightly conservative but guarantees correct precedence
            // in all cases — the TypeScript compiler will see the explicit
            // grouping and never misinterpret it.
            // -----------------------------------------------------------------
            Expr::Binary { left, op, right } => {
                let left_ts  = self.gen_expr(left);
                let right_ts = self.gen_expr(right);
                let op_ts    = gen_binop(op);
                format!("({} {} {})", left_ts, op_ts, right_ts)
            }

            // -----------------------------------------------------------------
            // Function call
            //   `name(arg1, arg2, …)`
            //
            // Generate each argument expression and join them with ", ".
            // -----------------------------------------------------------------
            Expr::Call { name, args } => {
                let args_ts: Vec<String> = args
                    .iter()
                    .map(|a| self.gen_expr(a))
                    .collect();
                format!("{}({})", name, args_ts.join(", "))
            }
        }
    }
}

// =============================================================================
// Operator mapping
// =============================================================================

/// Convert a Pico `BinOp` to the corresponding TypeScript operator string.
///
/// Notable differences between Pico and TypeScript:
///   • `==`  in Pico  →  `===`  in TypeScript  (strict equality, no type coercion)
///   • `!=`  in Pico  →  `!==`  in TypeScript  (strict not-equal)
///
/// All other operators are identical.
///
/// Returns `&'static str` because the operator strings are string literals
/// baked into the binary at compile time and therefore live for the entire
/// program (`'static` lifetime).
fn gen_binop(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        // IMPORTANT: Pico `==` becomes TypeScript `===` (strict equality)
        // TypeScript's `==` uses type coercion which can cause surprising bugs.
        // `===` is always the safer choice.
        BinOp::Eq  => "===",
        BinOp::Ne  => "!==",
        BinOp::Lt  => "<",
        BinOp::Gt  => ">",
        BinOp::Le  => "<=",
        BinOp::Ge  => ">=",
    }
}

// =============================================================================
// Public convenience function
// =============================================================================

/// Generate TypeScript source code from a Pico `Program` (AST).
///
/// This is the single public entry point for the code-generation phase.
/// It creates a `CodeGen`, calls `gen_program`, and returns the result.
///
/// Usage in `main.rs`:
/// ```rust
/// let typescript = codegen::generate(&program);
/// fs::write("output.ts", &typescript)?;
/// ```
pub fn generate(program: &Program) -> String {
    let mut codegen = CodeGen::new();
    codegen.gen_program(program)
}

// =============================================================================
// Tests
// =============================================================================
#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::tokenize;
    use crate::parser::Parser;

    /// Helper: lex + parse + generate in one step.
    fn compile(src: &str) -> String {
        let tokens = tokenize(src);
        let mut parser = Parser::new(tokens);
        let program = parser.parse();
        generate(&program)
    }

    #[test]
    fn test_let_becomes_const() {
        let ts = compile("let x = 42;");
        assert!(
            ts.contains("const x = 42;"),
            "expected 'const x = 42;' in:\n{}",
            ts
        );
    }

    #[test]
    fn test_print_becomes_console_log() {
        let ts = compile("let n = 5; print(n);");
        assert!(
            ts.contains("console.log(n);"),
            "expected 'console.log(n);' in:\n{}",
            ts
        );
    }

    #[test]
    fn test_function_signature() {
        let ts = compile("fn add(a, b) { return a + b; }");
        assert!(
            ts.contains("function add(a: any, b: any): any {"),
            "expected function signature in:\n{}",
            ts
        );
    }

    #[test]
    fn test_if_else_structure() {
        let ts = compile("let x = 1; if x > 0 { print(x); } else { print(x); }");
        // condition is wrapped in parentheses
        assert!(ts.contains("if ((x > 0))"), "expected if condition in:\n{}", ts);
        assert!(ts.contains("} else {"), "expected else in:\n{}", ts);
    }

    #[test]
    fn test_equality_operator_becomes_strict() {
        // Pico '==' must become TypeScript '==='
        let ts = compile("let x = 1; let y = 1; if x == y { print(x); }");
        assert!(
            ts.contains("==="),
            "expected strict equality '===' in:\n{}",
            ts
        );
        // And '!=' must become '!=='
        let ts2 = compile("let a = 1; let b = 2; if a != b { print(a); }");
        assert!(
            ts2.contains("!=="),
            "expected strict not-equal '!==' in:\n{}",
            ts2
        );
    }

    #[test]
    fn test_string_literal_output() {
        let ts = compile(r#"let s = "hello";"#);
        assert!(
            ts.contains(r#"const s = "hello";"#),
            "expected string literal in:\n{}",
            ts
        );
    }

    #[test]
    fn test_number_strips_dot_zero() {
        // Whole numbers should NOT have ".0" in the output
        let ts = compile("let n = 100;");
        assert!(
            ts.contains("const n = 100;"),
            "expected '100' (not '100.0') in:\n{}",
            ts
        );
    }

    #[test]
    fn test_float_number_kept() {
        let ts = compile("let pi = 3.14;");
        assert!(
            ts.contains("const pi = 3.14;"),
            "expected '3.14' in:\n{}",
            ts
        );
    }

    #[test]
    fn test_full_program() {
        let src = r#"
fn greet(name) {
    print(name);
}
let x = 10;
let y = 20;
let sum = x + y;
if sum > 25 {
    greet("Big number!");
} else {
    greet("Small number.");
}
"#;
        let ts = compile(src);
        // Check key pieces of the output
        assert!(ts.contains("function greet(name: any): any {"));
        assert!(ts.contains("const x = 10;"));
        assert!(ts.contains("const y = 20;"));
        assert!(ts.contains("const sum = (x + y);"));
        assert!(ts.contains("if ((sum > 25))"));
    }
}
